architecture: standalone
replica: 
  replicaCount: 1

auth: 
  enabled: true
  existingSecret: exosphere-redis-auth

master:
  persistence:
    size: 4Gi
  resources:
    limits:
      cpu: 1000m
      memory: 4096Mi
  configuration: |
    maxmemory 3gb
    maxmemory-policy volatile-ttl
    maxmemory-samples 10

metrics:
  enabled: true