version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["uv", "run", "run.py", "--mode", "production", "--workers", "2"]
