site_name: Docs Exosphere
site_description: Docs exosphere.host (An open-source infrastructure layer for background AI workflows/agents that is reliable, affordable, and effortless)
site_url: https://docs.exosphere.host
site_author: exosphere.host


repo_name: exospherehost/exospherehost
repo_url: https://github.com/exospherehost/exospherehost
edit_uri: edit/main/docs/docs

copyright: Copyright &copy; 2025 exosphere.host


theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: exosphere-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: exosphere-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  homepage: https://exosphere.host
  analytics:
    provider: google
    property: G-SZLXWPZSE5
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/exospherehost/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/exospherehost
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/zT92CAgvkj
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/exospherehost/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/exospherehost/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@exospherehost

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      type: date
  - llmstxt:
      markdown_description: |
        Exosphere is an open-source infrastructure platform for running AI agents and workflows at scale. It provides reliable execution, persistent state management, and failure handling for long-running AI processes.

        Core Components:
        - State Manager: FastAPI backend with MongoDB for workflow orchestration and state persistence
        - Dashboard: Next.js web interface for monitoring and managing workflows
        - Python SDK: Library for defining nodes, runtimes, and triggering workflows
        - Docker Compose: Quick local setup with cloud or local MongoDB options

        Key Features:
        - Define reusable nodes (agents, API calls, code) that can be plugged into any workflow
        - Create graph-based workflows with JSON configuration
        - Dynamic state creation at runtime with infinite parallel execution
        - Built-in retry policies and failure handling
        - Persistent state management across workflow executions
        - RESTful API for workflow management and monitoring

        Quick Setup: Use Docker Compose with cloud MongoDB (recommended) or local MongoDB for development. Set MONGO_URI, STATE_MANAGER_SECRET, and other environment variables. SDK requires EXOSPHERE_STATE_MANAGER_URI and EXOSPHERE_API_KEY to connect to running instance.
      sections:
        Introduction:
          - index.md
          - getting-started.md
          - exosphere/local-setup.md
          - docker-compose-setup.md
          - exosphere/state-manager-setup.md
          - exosphere/register-node.md
          - exosphere/create-runtime.md
          - exosphere/create-graph.md
          - exosphere/retry-policy.md
          - exosphere/trigger-graph.md
          - exosphere/dashboard.md
          - exosphere/signals.md
          - exosphere/architecture.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Local Setup: exosphere/local-setup.md
  - Docker Compose: docker-compose-setup.md
  - State Manager Setup: exosphere/state-manager-setup.md
  - Register Node: exosphere/register-node.md
  - Create Runtime: exosphere/create-runtime.md
  - Create Graph: exosphere/create-graph.md
  - Retry Policy: exosphere/retry-policy.md
  - Trigger Graph: exosphere/trigger-graph.md
  - Dashboard: exosphere/dashboard.md
  - Signals: exosphere/signals.md
  - Architecture: exosphere/architecture.md