site_name: Docs Exosphere
site_description: Docs exosphere.host (An open-source infrastructure layer for background AI workflows/agents that is reliable, affordable, and effortless)
site_url: https://docs.exosphere.host
site_author: exosphere.host


repo_name: exospherehost/exospherehost
repo_url: https://github.com/exospherehost/exospherehost
edit_uri: edit/main/docs/docs

copyright: Copyright &copy; 2025 exosphere.host


theme: 
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: exosphere-light 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: exosphere-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  homepage: https://exosphere.host
  analytics:
    provider: google
    property: G-SZLXWPZSE5
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/exospherehost/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/exospherehost
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JzCT6HRN
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/exospherehost/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/exospherehost/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@exospherehost

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Satellites:
    - Overview: satellites/index.md
    - exospherehost/deepseek-r1-distrill-llama-70b: satellites/exospherehost/deepseek-r1-distrill-llama-70b.md
    - exospherehost/get-files: satellites/exospherehost/get-files.md
    - exospherehost/parse-with-docling: satellites/exospherehost/parse-with-docling.md
    - exospherehost/call-webhook: satellites/exospherehost/call-webhook.md
    - exospherehost/forward-logs: satellites/exospherehost/forward-logs.md
    - exospherehost/move-file: satellites/exospherehost/move-file.md
    - exospherehost/send-alert: satellites/exospherehost/send-alert.md
    - exospherehost/send-email: satellites/exospherehost/send-email.md
  - Cluster: cluster.md
  - Examples: examples.md