name: Check Docs before PR merge

on:
    pull_request:
        branches:
            - main
        paths:
            - 'docs/**'

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Setup UV
              uses: astral-sh/setup-uv@v6 
            - name: Install dependencies
              working-directory: ./docs
              run: uv sync
            - name: Build documentation
              working-directory: ./docs
              run: uv run mkdocs build --strict