name: Check spells before PR merge

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: codespell . --skip="venv,*.lock,*.min.js,*.map,*.svg,*.png,*.jpg,*.jpeg, package.json, package-lock.json, node_modules,.git"
        continue-on-error: false

