name: Test Python SDK

on:
  pull_request:
    paths:
      - "python-sdk/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-sdk
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        name: Install uv

      - run: uv python install

      - run: uv sync --locked --dev

      - name: Run tests
        run: uvx --from pytest pytest -q